---
title: "test"
author: "Kwong Yu Chong, Jiahua Wang"
date: "2022-12-02"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
require(tidyverse)
require(kableExtra)
require(patchwork)
require(GGally)
require(corrplot)
require(RColorBrewer)
require(tidymodels)
require(ranger)
set.seed(666)
```

# read all CV results of all models
```{r}
extract_fold_loss = function(path='./data'){
  Kmeans_split_fold_loss = c()
  block_split_fold_loss = c()
  for (f_name in list.files(path)){
    df = readRDS(paste0(path, '/',f_name)) %>% .$fold_loss
    df[[f_name]] = df$accuracy
    df = df[, c('fold', f_name)]
    if (grepl( 'Kmeans', f_name, fixed = TRUE)){
      Kmeans_split_fold_loss = c(Kmeans_split_fold_loss, df)
    }else{
      block_split_fold_loss = c(block_split_fold_loss, df)
    }
  }
  Kmeans_fold_loss = do.call(cbind, Kmeans_split_fold_loss) %>% data.frame() %>% select(fold, contains('Kmeans'))
  block_fold_loss = do.call(cbind, block_split_fold_loss) %>% data.frame() %>% select(fold, contains('Block'))
  return(list('Kmeans'=Kmeans_fold_loss,
              'Block' = block_fold_loss))
}


CV_res = extract_fold_loss()
kmeans_cv_res = CV_res$Kmeans
colnames(kmeans_cv_res) = c('Fold', 'LDA',  'Logistic Regression', 'Naive Bayes', 
                            'QDA','Random Forest', 'XGBoost')

block_cv_res = CV_res$Block
colnames(block_cv_res) = c('Fold', 'LDA', 'Logistic Regression', 'Naive Bayes', 
                            'QDA','Random Forest', 'XGBoost')
block_cv_res %>% colMeans()


kmeans_cv_res %>% round(3)%>% summarise(Fold = c(Fold, ' '),across(where(is.numeric), ~ c(., round(mean(.),3)))) %>%
  relocate(LDA, .before = QDA)%>%
  kbl(caption = "<center><strong>K-means Split: CV Accuracy<center><strong>",
      escape = FALSE,
      format = 'html',) %>%
  row_spec(dim(kmeans_cv_res)[1]+1, bold = T) %>%
  row_spec(dim(kmeans_cv_res)[1], extra_css = "border-bottom: 1px solid") %>%
  kable_classic(full_width = F, html_font = "Cambria")
```

```{r}
block_cv_res %>% round(3)%>% summarise(Fold = c(Fold, ' '),across(where(is.numeric), ~ c(., round(mean(.),3)))) %>%
  relocate(LDA, .before = QDA)%>%
  #relocate('Logistic Regression (Reg)', .after = 'Logistic Regression')%>%
  kbl(caption = "<center><strong>Block Split: CV Accuracy<center><strong>",
      escape = FALSE,
      format = 'html',) %>%
  row_spec(dim(block_cv_res)[1]+1, bold = T) %>%
  row_spec(dim(block_cv_res)[1], extra_css = "border-bottom: 1px solid") %>%
  kable_classic(full_width = F, html_font = "Cambria")

```

```{r}
a = read_rds('./data/Kmeans_xgboost_res.rds')
xgboost = list()
for (k in 1:5){
  xgboost = rbind(xgboost, a$workflow$.metrics[[k]])
}
xgboost = xgboost %>% filter(.config %in% (a$workflow %>%select_best( "accuracy")%>%pull(.config)))
xgboost %>% filter(.metric=='accuracy') %>% pull(.estimate) %>% mean()


```
