---
title: "proj2"
author: "Kwong Yu Chong, Jiahua Wang"
date: "2022-11-28"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
require(tidyverse)
require(kableExtra)
require(patchwork)
require(GGally)
require(corrplot)
```

# Read Data
```{r}
img1 = read.table("imagem1.txt")
img2 = read.table("imagem2.txt")
img3 = read.table("imagem3.txt")
```

```{r}
col_name = c("Y","X","Label","NDAI","SD","CORR","Rad_Df",
             "Rad_Cf","Rad_Bf","Rad_Af","Rad_An")
colnames(img1) = col_name
colnames(img2) = col_name
colnames(img3) = col_name

full_img = rbind(img1, img2, img3)
```

```{r}
img1 %>% head()
```

# Summarize the data

###  % pixcel by label
```{r}
tbl1= img1 %>% group_by(Label) %>% count() %>%
  ungroup() %>% 
  mutate(Image1 = round(n / sum(n)*100,1)) %>% select(Label, Image1)
tbl2= img2 %>% group_by(Label) %>% count() %>%
  ungroup() %>% 
  mutate(Image2 = round(n / sum(n)*100,1)) %>% select(Label, Image2)
tbl3= img3 %>% group_by(Label) %>% count() %>%
  ungroup() %>% 
  mutate(Image3 = round(n / sum(n)*100,1)) %>% select(Label, Image3)

tbl1 %>% left_join(tbl2, by='Label') %>% left_join(tbl3, by='Label') %>%
  mutate(Label=ifelse(Label==1, 'Cloudy (1)', ifelse(Label==-1, 'Cloud-free (-1)', 'Unlabeled (0)')))%>%
  arrange(Label)%>%
  kbl(caption = "<center><strong>Pixels By Label (%)<center><strong>",
      escape = FALSE,
      format = 'html',) %>%
  kable_classic(full_width = F, html_font = "Cambria")
```

### Plot Maps
```{r}
img1 %>% 
  mutate(Label=
           as.factor(ifelse(Label==1, 'Cloudy (1)',
                  ifelse(Label==-1, 'Cloud-free (-1)',
                         'Unlabeled (0)')))) %>% 
  ggplot() +
  geom_raster(aes(x=X, y=Y, fill=Label)) +
  scale_fill_manual(values=c("Cloudy (1)"='white', 
                             'Cloud-free (-1)'='grey',
                             'Unlabeled (0)'='black'))+
  labs(title='Image 1 Label', x='X-coordinate', y='Y-coordinate')+
   theme(plot.title = element_text(hjust = 0.5), legend.position="none")

img2 %>% 
  mutate(Label=
           as.factor(ifelse(Label==1, 'Cloudy (1)',
                  ifelse(Label==-1, 'Cloud-free (-1)',
                         'Unlabeled (0)')))) %>% 
  ggplot() +
  geom_raster(aes(x=X, y=Y, fill=Label)) +
  scale_fill_manual(values=c("Cloudy (1)"='white', 
                             'Cloud-free (-1)'='grey',
                             'Unlabeled (0)'='black'))+
  labs(title='Image 2 Label', x='X-coordinate', y='Y-coordinate')+
   theme(plot.title = element_text(hjust = 0.5), legend.position="none")

img3 %>% 
  mutate(Label=
           as.factor(ifelse(Label==1, 'Cloudy (1)',
                  ifelse(Label==-1, 'Cloud-free (-1)',
                         'Unlabeled (0)')))) %>% 
  ggplot() +
  geom_raster(aes(x=X, y=Y, fill=Label)) +
  scale_fill_manual(values=c("Cloudy (1)"='white', 
                             'Cloud-free (-1)'='grey',
                             'Unlabeled (0)'='black'))+
  labs(title='Image 3 Label', x='X-coordinate', y='Y-coordinate')+
   theme(plot.title = element_text(hjust = 0.5),legend.position="none")
```

# EDA
```{r}
col <- colorRampPalette(c("#BB4444", "#EE9988", "#FFFFFF", "#77AADD", "#4477AA"))
full_img %>% select(-c(X,Y,Label)) %>% cor() %>%
  corrplot::corrplot(method="color", col=col(200),  
     diag=T,  tl.srt=45, tl.col = 'black', tl.cex = 0.75,mar=c(0,0,2,0),
     type="upper", order="hclust", 
     title='Feature Correlation', 
         addCoef.col = "black",  outline=T,
         )
```

```{r}
tbl_data = full_img %>% filter(Label!=0) %>% cor() %>% .[-c(1,2,3),3] %>% round(.,2)

data.frame('value'=tbl_data) %>% arrange(desc(value))%>%kbl(
  caption = "<center><strong>Correlation with Label<center><strong>",
  escape = FALSE,
  format = 'html',
  table.attr = "style='width:25%;'") %>%
  kable_classic(full_width = T, html_font = "Cambria",) 
```

```{r}
plot_data = full_img %>% 
  filter(Label != 0) %>%
  mutate(Label = ifelse(Label==1, 'Cloudy', 'Cloud-free'))

p1 = plot_data%>%
  ggplot() + geom_density(aes(x=CORR, fill=Label), alpha=0.5) 
p2 = plot_data%>%
  ggplot() + geom_density(aes(x=NDAI, fill=Label), alpha=0.5) 
p3 = plot_data%>%
  ggplot() + geom_density(aes(x=log(SD), fill=Label), alpha=0.5) 
p4 = plot_data%>%
  ggplot() + geom_density(aes(x=Rad_Af, fill=Label), alpha=0.5) 

p1 + p2 + p3 + p4 + plot_layout(nrow=2, guides = "collect") + 
  plot_annotation(title = 'Density of Features By Label',
                  theme=theme(plot.title = element_text(hjust = 0.5))) 
```

## Two-sample Kolmogorov–Smirnov statistics
```{r}
full_img_cloudy = full_img %>% filter(Label==1)
full_img_not_cloudy = full_img %>% filter(Label==-1)

var_names = full_img %>% select(-c(X, Y, Label)) %>% colnames() 
KS_stat = matrix(nrow=length(var_names))
rownames(KS_stat) = var_names
colnames(KS_stat) = 'Statistics'

for (var in var_names){
  cloudy_density = full_img_cloudy %>% select(var) %>% as.matrix()%>% density()
  not_cloudy_density = full_img_not_cloudy %>% select(var)%>% as.matrix()%>% density()
  min_x = min(cloudy_density$x , not_cloudy_density$x)
  max_x = max(cloudy_density$x , not_cloudy_density$x)
  cloudy_density = full_img_cloudy %>% select(var) %>% as.matrix()%>% 
    density(from=min_x, to=max_x)
  not_cloudy_density = full_img_not_cloudy %>% select(var)%>% as.matrix()%>%
    density(from=min_x, to=max_x)
  
  x_diff = not_cloudy_density$x %>% diff() %>% .[1]
  KS = tibble(x=cloudy_density$x, cloudy=cloudy_density$y, not_cloudy= not_cloudy_density$y)%>%
    mutate(cloudy = cumsum(cloudy *x_diff),
           not_cloudy= cumsum(not_cloudy *x_diff))%>%
    mutate(diff = abs(cloudy - not_cloudy))%>%
    select(diff)%>%max()
  KS_stat[var,1] = KS
}
KS_stat %>% round(.,2) %>% data.frame() %>% arrange(desc(Statistics))%>%kbl(
  caption = "<center><strong>Two-sample K-S Test: cloudy VS cloud-free<center><strong>",
  escape = FALSE,
  format = 'html',
  table.attr = "style='width:45%;'") %>%
  kable_classic(full_width = T, html_font = "Cambria",) 
```

```{r}

```




















